// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MvcConsole.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240308144922_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Genere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Generi");
                });

            modelBuilder.Entity("Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Eta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Videogioco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenereId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenereId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Videogiochi");
                });

            modelBuilder.Entity("Voti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideogiocoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.HasIndex("VideogiocoId");

                    b.ToTable("Voti");
                });

            modelBuilder.Entity("Videogioco", b =>
                {
                    b.HasOne("Genere", "Genere")
                        .WithMany()
                        .HasForeignKey("GenereId");

                    b.HasOne("Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.Navigation("Genere");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Voti", b =>
                {
                    b.HasOne("Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId");

                    b.HasOne("Videogioco", "Videogioco")
                        .WithMany()
                        .HasForeignKey("VideogiocoId");

                    b.Navigation("Utente");

                    b.Navigation("Videogioco");
                });
#pragma warning restore 612, 618
        }
    }
}
